# Generated by Django 5.1.6 on 2025-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearbeitet_bild', models.TextField()),
                ('bildnummer', models.IntegerField()),
                ('breite', models.IntegerField()),
                ('datum', models.DateTimeField()),
                ('db', models.TextField()),
                ('description', models.TextField()),
                ('fotografen', models.TextField()),
                ('hoehe', models.IntegerField()),
                ('suchtext', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
